export const baseURL = 'https://norma.nomoreparties.space/api/'
export const ingredients = 'ingredients'        // для списка ингредиентов.
export const orders = 'orders'                  // для номера заказа.
export const login = 'auth/login'               // для авторизации.
export const user = 'auth/user'                 // для данных пользователя.
export const register = 'auth/register'         // для регистрации пользователя.
export const logout = 'auth/logout'             // для выхода из системы.
export const token = 'auth/token'               // для обновления токена.
export const reset = 'password-reset'           // для сброса пароля
export const password = 'password-reset/reset'  // для нового пароля