export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const ADD_BUN = "ADD_BUN";
export const REORDER_INGREDIENT = "REORDER_INGREDIENT";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS"